# Generated by Django 3.2 on 2023-06-22 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=80, verbose_name='Apellido')),
                ('telefono', models.IntegerField(verbose_name='Teléfono')),
                ('domicilio', models.CharField(max_length=80, verbose_name='Domicilio')),
                ('email', models.CharField(max_length=30, verbose_name='Email de contacto')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Veterinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30, verbose_name='Veterinaria')),
                ('direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('telefono', models.IntegerField(verbose_name='Telefono')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreServicio', models.CharField(choices=[('CASTRACIONES', 'Castraciones'), ('VACUNACION', 'Vacunacion'), ('BANIO', 'Baño'), ('PELUQUERIA', 'Peluqueria'), ('CONSULTA', 'Consulta')], max_length=30, verbose_name='Nombre del servicio')),
                ('veterinaria', models.ManyToManyField(to='portal.Veterinaria', verbose_name='Veterinaria')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(choices=[('PERRO', 'Perro'), ('GATO', 'Gato'), ('AVE', 'Ave')], max_length=50, verbose_name='Especie')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('raza', models.CharField(max_length=50, verbose_name='Raza')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('tamanio', models.CharField(max_length=50, verbose_name='Tamanio')),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='veterinaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.veterinaria'),
        ),
    ]
