# Generated by Django 3.2 on 2023-06-16 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vacunas',
            new_name='Vacuna',
        ),
        migrations.RenameField(
            model_name='vacuna',
            old_name='vacunas',
            new_name='vacuna',
        ),
        migrations.RemoveField(
            model_name='mascota',
            name='vacunas',
        ),
        migrations.AddField(
            model_name='mascota',
            name='vacuna',
            field=models.ManyToManyField(to='portal.Vacuna', verbose_name='Vacunas'),
        ),
        migrations.AlterField(
            model_name='mascota',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.cliente', verbose_name='Cliente'),
        ),
    ]
