# Generated by Django 3.2 on 2023-06-09 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='veterinaria',
            field=models.ManyToManyField(to='portal.Veterinaria', verbose_name='Veterinaria'),
        ),
    ]
